# Generated by Django 3.1.4 on 2021-01-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CoolingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Система охлаждения',
                'verbose_name_plural': 'Системы охлаждения',
            },
        ),
        migrations.CreateModel(
            name='FrontBrakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Передние тормоза',
                'verbose_name_plural': 'Передние тормоза',
            },
        ),
        migrations.CreateModel(
            name='LaunchSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Система запуска',
                'verbose_name_plural': 'Системы запуска',
            },
        ),
        migrations.CreateModel(
            name='RearBrakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Задние тормоза',
                'verbose_name_plural': 'Задние тормоза',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Трансмиссия',
                'verbose_name_plural': 'Трансмиссия',
            },
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('availability', models.CharField(max_length=50, verbose_name='Наличие')),
                ('engine_capacity', models.CharField(max_length=50, verbose_name='Объем двигателя')),
                ('fuel', models.CharField(max_length=50, verbose_name='Топливо')),
                ('fuel_consumption', models.CharField(max_length=50, verbose_name='Расход топлива')),
                ('front_wheel', models.CharField(max_length=100, verbose_name='Переднее колесо')),
                ('rear_wheel', models.CharField(max_length=100, verbose_name='Заднее колесо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motocatalog.category', verbose_name='Категория')),
                ('cooling_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.coolingsystem', verbose_name='Система охлаждения')),
                ('front_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.frontbrakes', verbose_name='Передние тормоза')),
                ('launch_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.launchsystem', verbose_name='Система запуска')),
                ('rear_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.rearbrakes', verbose_name='Задние тормоза')),
                ('transmission', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.transmission', verbose_name='Трансмиссия ')),
            ],
            options={
                'verbose_name': 'Скутер',
                'verbose_name_plural': 'Скутеры',
            },
        ),
        migrations.CreateModel(
            name='QuadBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('availability', models.CharField(max_length=50, verbose_name='Наличие')),
                ('engine_capacity', models.CharField(max_length=50, verbose_name='Объем двигателя')),
                ('fuel', models.CharField(max_length=50, verbose_name='Топливо')),
                ('fuel_consumption', models.CharField(max_length=50, verbose_name='Расход топлива')),
                ('front_wheel', models.CharField(max_length=100, verbose_name='Переднее колесо')),
                ('rear_wheel', models.CharField(max_length=100, verbose_name='Заднее колесо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motocatalog.category', verbose_name='Категория')),
                ('cooling_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.coolingsystem', verbose_name='Система охлаждения')),
                ('front_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.frontbrakes', verbose_name='Передние тормоза')),
                ('launch_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.launchsystem', verbose_name='Система запуска')),
                ('rear_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.rearbrakes', verbose_name='Задние тормоза')),
                ('transmission', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.transmission', verbose_name='Трансмиссия ')),
            ],
            options={
                'verbose_name': 'Квадроцикл',
                'verbose_name_plural': 'Квадроциклы',
            },
        ),
        migrations.CreateModel(
            name='PitBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('availability', models.CharField(max_length=50, verbose_name='Наличие')),
                ('engine_capacity', models.CharField(max_length=50, verbose_name='Объем двигателя')),
                ('fuel', models.CharField(max_length=50, verbose_name='Топливо')),
                ('fuel_consumption', models.CharField(max_length=50, verbose_name='Расход топлива')),
                ('front_wheel', models.CharField(max_length=100, verbose_name='Переднее колесо')),
                ('rear_wheel', models.CharField(max_length=100, verbose_name='Заднее колесо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motocatalog.category', verbose_name='Категория')),
                ('cooling_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.coolingsystem', verbose_name='Система охлаждения')),
                ('front_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.frontbrakes', verbose_name='Передние тормоза')),
                ('launch_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.launchsystem', verbose_name='Система запуска')),
                ('rear_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.rearbrakes', verbose_name='Задние тормоза')),
                ('transmission', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.transmission', verbose_name='Трансмиссия ')),
            ],
            options={
                'verbose_name': 'Питбайк',
                'verbose_name_plural': 'Питбайки',
            },
        ),
        migrations.CreateModel(
            name='Moped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('availability', models.CharField(max_length=50, verbose_name='Наличие')),
                ('engine_capacity', models.CharField(max_length=50, verbose_name='Объем двигателя')),
                ('fuel', models.CharField(max_length=50, verbose_name='Топливо')),
                ('fuel_consumption', models.CharField(max_length=50, verbose_name='Расход топлива')),
                ('front_wheel', models.CharField(max_length=100, verbose_name='Переднее колесо')),
                ('rear_wheel', models.CharField(max_length=100, verbose_name='Заднее колесо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motocatalog.category', verbose_name='Категория')),
                ('cooling_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.coolingsystem', verbose_name='Система охлаждения')),
                ('front_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.frontbrakes', verbose_name='Передние тормоза')),
                ('launch_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.launchsystem', verbose_name='Система запуска')),
                ('rear_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.rearbrakes', verbose_name='Задние тормоза')),
                ('transmission', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.transmission', verbose_name='Трансмиссия ')),
            ],
            options={
                'verbose_name': 'Мопед',
                'verbose_name_plural': 'Мопеды',
            },
        ),
        migrations.CreateModel(
            name='CrossTechnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('availability', models.CharField(max_length=50, verbose_name='Наличие')),
                ('engine_capacity', models.CharField(max_length=50, verbose_name='Объем двигателя')),
                ('fuel', models.CharField(max_length=50, verbose_name='Топливо')),
                ('fuel_consumption', models.CharField(max_length=50, verbose_name='Расход топлива')),
                ('front_wheel', models.CharField(max_length=100, verbose_name='Переднее колесо')),
                ('rear_wheel', models.CharField(max_length=100, verbose_name='Заднее колесо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motocatalog.category', verbose_name='Категория')),
                ('cooling_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.coolingsystem', verbose_name='Система охлаждения')),
                ('front_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.frontbrakes', verbose_name='Передние тормоза')),
                ('launch_system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.launchsystem', verbose_name='Система запуска')),
                ('rear_brakes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.rearbrakes', verbose_name='Задние тормоза')),
                ('transmission', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motocatalog.transmission', verbose_name='Трансмиссия ')),
            ],
            options={
                'verbose_name': 'Кроссовая техника',
                'verbose_name_plural': 'Кроссовая техника',
            },
        ),
    ]
